# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a set of commands using the runners shell
    - name: build
      run: |
        sudo -E apt-get update
        sudo -E apt-get -y libncurses5 libncurses5-dev m4 bison gawk flex libstdc++6-4.4-dev g++-4.4 g++ gengetopt git (or git-core) gitk zlib1g-dev autoconf autopoint (or gettext) libtool shtool autogen mtd-utils intltool sharutils docbook-xsl-* libstdc++5 texinfo dos2unix (or tofrodos) xsltproc uboot-mkimage device-tree-compiler python 2.7 or above. qemu gperf liblzo2-dev uuid-dev build-essential lzma-dev liblzma-dev lzma binutils-dev patch cmake intltool libglib2.0-dev gtk-doc-tools libc6-i386 lib32stdc++6 lib32z1 libelf1:i386 libncurses5:i386 ia32-libs libc6-dev-i386
        cd /home
        git clone https://github.com/MerlinRdev/acrh17-merlin.git
        
        cd acrh17-merlin
        cd tools
        sudo tar -jxvf  openwrt-gcc463.arm.tar.bz2 -C /opt
        
        sudo echo "PATH=/opt/openwrt-gcc463.mips/bin:$PATH"  >> /etc/profile
        source /etc/profile
        
        cd /home/acrh17-merlin
        
        cd release/src
        
        make acrh17
        echo "::set-output name=status::success"
        
    - name: Upload bin directory
      uses: actions/upload-artifact@master
      if: steps.compile.outputs.status == 'success' && env.UPLOAD_BIN_DIR == 'true'
      with:
        name: ACRH17_bin
        path: acrh17-merlin/bin  
        
        
        
        
        
