# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a set of commands using the runners shell
    - name: build
      run: |
        sudo -E apt-get update
        sudo apt-get install autoconf automake bash bison bzip2 diffutils file flex m4 g++ gawk groff-base libncurses-dev libtool libslang2 make patch perl pkg-config shtool subversion tar texinfo zlib1g zlib1g-dev git-core gettext libexpat1-dev libssl-dev cvs gperf unzip python libxml-parser-perl gcc-multilib gconf-editor libxml2-dev g++-5 g++-multilib gitk libncurses5 mtd-utils libncurses5-dev libvorbis-dev g++-5-multilib git autopoint autogen sed lib32z1-dev lib32stdc++6 build-essential intltool libelf1:i386 libglib2.0-dev xutils-dev libltdl7-dev libproxy-dev
        cd /home
        git clone https://github.com/MerlinRdev/acrh17-merlin.git
        
        cd acrh17-merlin
        cd tools
        sudo tar -jxvf  openwrt-gcc463.arm.tar.bz2 -C /opt
        
        sudo echo "PATH=/opt/openwrt-gcc463.mips/bin:$PATH"  >> /etc/profile
        source /etc/profile
        
        cd /home/acrh17-merlin
        
        cd release/src
        
        make acrh17
        echo "::set-output name=status::success"
        
    - name: Upload bin directory
      uses: actions/upload-artifact@master
      if: steps.compile.outputs.status == 'success' && env.UPLOAD_BIN_DIR == 'true'
      with:
        name: ACRH17_bin
        path: acrh17-merlin/bin  
        
        
        
        
        
